/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaisieDonneesRouteImport } from './routes/saisie-donnees'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InscriptionDonneurRouteImport } from './routes/inscription-donneur'
import { Route as DisponibiliteRouteImport } from './routes/disponibilite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SaisieDonneesRoute = SaisieDonneesRouteImport.update({
  id: '/saisie-donnees',
  path: '/saisie-donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionDonneurRoute = InscriptionDonneurRouteImport.update({
  id: '/inscription-donneur',
  path: '/inscription-donneur',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponibiliteRoute = DisponibiliteRouteImport.update({
  id: '/disponibilite',
  path: '/disponibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/disponibilite': typeof DisponibiliteRoute
  '/inscription-donneur': typeof InscriptionDonneurRoute
  '/mcp': typeof McpRoute
  '/saisie-donnees': typeof SaisieDonneesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/disponibilite': typeof DisponibiliteRoute
  '/inscription-donneur': typeof InscriptionDonneurRoute
  '/mcp': typeof McpRoute
  '/saisie-donnees': typeof SaisieDonneesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/disponibilite': typeof DisponibiliteRoute
  '/inscription-donneur': typeof InscriptionDonneurRoute
  '/mcp': typeof McpRoute
  '/saisie-donnees': typeof SaisieDonneesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/contact'
    | '/disponibilite'
    | '/inscription-donneur'
    | '/mcp'
    | '/saisie-donnees'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/contact'
    | '/disponibilite'
    | '/inscription-donneur'
    | '/mcp'
    | '/saisie-donnees'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/contact'
    | '/disponibilite'
    | '/inscription-donneur'
    | '/mcp'
    | '/saisie-donnees'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ContactRoute: typeof ContactRoute
  DisponibiliteRoute: typeof DisponibiliteRoute
  InscriptionDonneurRoute: typeof InscriptionDonneurRoute
  McpRoute: typeof McpRoute
  SaisieDonneesRoute: typeof SaisieDonneesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saisie-donnees': {
      id: '/saisie-donnees'
      path: '/saisie-donnees'
      fullPath: '/saisie-donnees'
      preLoaderRoute: typeof SaisieDonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-donneur': {
      id: '/inscription-donneur'
      path: '/inscription-donneur'
      fullPath: '/inscription-donneur'
      preLoaderRoute: typeof InscriptionDonneurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disponibilite': {
      id: '/disponibilite'
      path: '/disponibilite'
      fullPath: '/disponibilite'
      preLoaderRoute: typeof DisponibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ContactRoute: ContactRoute,
  DisponibiliteRoute: DisponibiliteRoute,
  InscriptionDonneurRoute: InscriptionDonneurRoute,
  McpRoute: McpRoute,
  SaisieDonneesRoute: SaisieDonneesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
